// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using StarTEDSystem.Entities;

namespace StarTEDSystem.DAL
{
    public partial class StarTEDContext : DbContext
    {
        public StarTEDContext()
        {
        }

        public StarTEDContext(DbContextOptions<StarTEDContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<ProgramCourse> ProgramCourses { get; set; }
        public virtual DbSet<School> Schools { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("Latin1_General_CI_AS");

            modelBuilder.Entity<Program>(entity =>
            {
                entity.HasIndex(e => e.SchoolCode, "IX_SchoolCode");

                entity.Property(e => e.DiplomaName)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.InternationalTuition).HasColumnType("money");

                entity.Property(e => e.ProgramName)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.SchoolCode)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Tuition).HasColumnType("money");

                entity.HasOne(d => d.SchoolCodeNavigation)
                    .WithMany(p => p.Programs)
                    .HasForeignKey(d => d.SchoolCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_dbo.Programs_dbo.Schools_SchoolCode");
            });

            modelBuilder.Entity<ProgramCourse>(entity =>
            {
                entity.HasIndex(e => e.CourseID, "IX_CourseID");

                entity.HasIndex(e => e.ProgramID, "IX_ProgramID");

                entity.HasIndex(e => new { e.ProgramID, e.CourseID }, "UN_dbo.ProgramCourses_ProgramIDCourseID")
                    .IsUnique();

                entity.Property(e => e.Comments).HasMaxLength(50);

                entity.Property(e => e.CourseID)
                    .IsRequired()
                    .HasMaxLength(7)
                    .IsUnicode(false);

                entity.HasOne(d => d.Program)
                    .WithMany(p => p.ProgramCourses)
                    .HasForeignKey(d => d.ProgramID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_dbo.ProgramCourses_dbo.Programs_ProgramID");
            });

            modelBuilder.Entity<School>(entity =>
            {
                entity.HasKey(e => e.SchoolCode)
                    .HasName("PK_dbo.Schools");

                entity.Property(e => e.SchoolCode)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.SchoolName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}