// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace StarTEDSystem.Entities
{
    public partial class Program
    {
        public Program()
        {
            ProgramCourses = new HashSet<ProgramCourse>();
        }

        public int ProgramID { get; set; }
        public string ProgramName { get; set; }
        public string DiplomaName { get; set; }
        public string SchoolCode { get; set; }
        public decimal Tuition { get; set; }
        public decimal InternationalTuition { get; set; }

        public virtual School SchoolCodeNavigation { get; set; }
        public virtual ICollection<ProgramCourse> ProgramCourses { get; set; }
    }
}