// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace StarTEDSystem.Entities
{
    public partial class Program
    {
        public Program()
        {
            ProgramCourses = new HashSet<ProgramCourse>();
        }

        private decimal _InternationalTution;
        private decimal _Tution;



        public int ProgramID { get; set; }
        public string ProgramName { get; set; }
        public string DiplomaName { get; set; }
        public string SchoolCode { get; set; }
        public decimal Tuition {
            get { return decimal.Parse(_Tution.ToString("0.00"));}
            set { _Tution = value; } 
        }

        public decimal InternationalTuition
        {
            get { return decimal.Parse(_InternationalTution.ToString("0.00")); }
            set { _InternationalTution = value; }
        }
        public virtual School SchoolCodeNavigation { get; set; }
        public virtual ICollection<ProgramCourse> ProgramCourses { get; set; }
    }
}